// <auto-generated>
// This file is generated by scripts/bump-version.sh.
// Do not edit manually.
// </auto-generated>

namespace PostHogUnity
{
    static partial class SdkInfo
    {
        /// <summary>
        /// The current SDK version.
        /// </summary>
        public const string Version = "0.1.1";
    }
}
