#!/bin/bash

# ./scripts/bump-version.sh <new version>
# eg ./scripts/bump-version.sh "0.2.0"
#
# Syncs the version from the root package.json (managed by changesets) to all
# platform-specific files:
#   - com.posthog.unity/package.json (Unity Package Manager)
#   - com.posthog.unity/Runtime/Utilities/SdkInfo.Generated.cs (runtime version constant)
#   - com.posthog.unity/CHANGELOG.md (symlink to root, no action needed)

set -eux

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR/.."

NEW_VERSION="$1"

# Update the Unity package.json version using node (no jq dependency)
node -e "
  const fs = require('fs');
  const pkg = JSON.parse(fs.readFileSync('com.posthog.unity/package.json', 'utf8'));
  pkg.version = '$NEW_VERSION';
  fs.writeFileSync('com.posthog.unity/package.json', JSON.stringify(pkg, null, 4) + '\n');
"

echo "✓ Updated com.posthog.unity/package.json to version $NEW_VERSION"

# Generate SdkInfo.Generated.cs with the new version
cat > com.posthog.unity/Runtime/Utilities/SdkInfo.Generated.cs << EOF
// <auto-generated>
// This file is generated by scripts/bump-version.sh.
// Do not edit manually.
// </auto-generated>

namespace PostHogUnity
{
    static partial class SdkInfo
    {
        /// <summary>
        /// The current SDK version.
        /// </summary>
        public const string Version = "$NEW_VERSION";
    }
}
EOF

echo "✓ Updated SdkInfo.Generated.cs to version $NEW_VERSION"

# Note: com.posthog.unity/CHANGELOG.md is a symlink to ../CHANGELOG.md
# so no copy is needed.
