#!/bin/bash

# ./scripts/bump-version.sh <new version>
# eg ./scripts/bump-version.sh "0.2.0"
#
# Syncs the version from the tracking package.json to all platform-specific files.
# The tracking/package.json is the source of truth for changesets.
# This script syncs that version to the Unity package.json and generated code.

set -eux

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR/.."

NEW_VERSION="$1"

# Update the Unity package.json version (the source of truth for UPM)
jq --arg version "$NEW_VERSION" '.version = $version' com.posthog.unity/package.json > com.posthog.unity/package.json.tmp
mv com.posthog.unity/package.json.tmp com.posthog.unity/package.json

echo "✓ Updated com.posthog.unity/package.json to version $NEW_VERSION"

# Generate SdkInfo.Generated.cs with the new version
cat > com.posthog.unity/Runtime/Utilities/SdkInfo.Generated.cs << EOF
// <auto-generated>
// This file is generated by scripts/bump-version.sh from package.json.
// Do not edit manually.
// </auto-generated>

namespace PostHogUnity
{
    static partial class SdkInfo
    {
        /// <summary>
        /// The current SDK version.
        /// </summary>
        public const string Version = "$NEW_VERSION";
    }
}
EOF

echo "✓ Updated SdkInfo.Generated.cs to version $NEW_VERSION"

# Copy root CHANGELOG.md to package directory for UPM
if [ -f "CHANGELOG.md" ]; then
    cp CHANGELOG.md com.posthog.unity/CHANGELOG.md
    echo "✓ Copied CHANGELOG.md to com.posthog.unity/"
fi
